- name: Debug environment variables
  run: |
    echo "DB_HOST: ${{ secrets.DB_HOST }}"
    echo "DB_PORT: ${{ secrets.DB_PORT }}"
    echo "DB_NAME: ${{ secrets.DB_NAME }}"
    echo "DB_USER: ${{ secrets.DB_USER }}"
